version: '3.8'

services:
  pdp-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - ".env"
    environment:
      POSTGRESQL_DSN: ${DOCKER_POSTGRESQL_DSN}
      MINIO_ENDPOINT: ${DOCKER_MINIO_ENDPOINT}
      KEYCLOAK_HOST_URL: https://pdp-keycloak:8443
      KEYCLOAK_PUBLIC_URL: https://${KC_HOSTNAME}:${KEYCLOAK_PORT}
      KEYCLOAK_CA_BUNDLE: /opt/certs/keycloak/cert.pem
    volumes:
      - .:/work
    networks:
      - pdp-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

  pdp-keycloak:
    build:
      context: .
      dockerfile: Dockerfile_keycloak.dockerfile
    container_name: keycloak
    restart: always
    environment:
      KC_DB: ${KC_DB}
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_NAME: ${KC_DB_NAME}
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_PORT: ${KEYCLOAK_PORT}
      KC_HOSTNAME_STRICT: "true"
      KC_HOSTNAME_STRICT_HTTPS: "true"
      KC_HTTP_ENABLED: "false"
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/certs/cert.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/certs/key.pem
      KC_LOG_LEVEL: ${KC_LOG_LEVEL}
      KC_METRICS_ENABLED: ${KC_METRICS_ENABLED}
      KC_HEALTH_ENABLED: ${KC_HEALTH_ENABLED}
      KC_FEATURES: ${KC_FEATURES}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "${KEYCLOAK_PORT}:8443"
    env_file:
      - ".env"
    networks:
      - pdp-network
    volumes:
      - .:/work:ro #needed for getting aws certificates which let communication with postgres
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    command: start --import-realm
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: 768M
        reservations:
          cpus: '0.3'
          memory: 512M

networks:
  pdp-network:
    name: pdp-network
    driver: bridge
