version: '3.8'

services:
  pdp-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - ".env"
    depends_on:
      - pdp-db
      - pdp-minio
      - pdp-keycloak
    environment:
      POSTGRESQL_DSN: ${DOCKER_POSTGRESQL_DSN}
      MINIO_ENDPOINT: ${DOCKER_MINIO_ENDPOINT}
      KEYCLOACK_HOST_URL: ${DOCKER_KEYCLOACK_HOST_URL}
    volumes:
      - .:/work
    networks:
      - pdp-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

  pdp-keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: keycloak
    restart: always
    environment:
      KC_DB: ${KC_DB}
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_NAME: ${KC_DB_NAME}
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_PORT: ${KC_HOSTNAME_PORT}
      KC_HOSTNAME_STRICT: ${KC_HOSTNAME_STRICT}
      KC_HOSTNAME_STRICT_HTTPS: ${KC_HOSTNAME_STRICT_HTTPS}
      KC_LOG_LEVEL: ${KC_LOG_LEVEL}
      KC_METRICS_ENABLED: ${KC_METRICS_ENABLED}
      KC_HEALTH_ENABLED: ${KC_HEALTH_ENABLED}
      KC_FEATURES: ${KC_FEATURES}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "${KEYCLOAK_PORT}:8080"
    env_file:
      - ".env"
    depends_on:
      - pdp-db
    networks:
      - pdp-network
    volumes:
      - .:/work:ro
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    command: start-dev --http-enabled=true --import-realm
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: 768M
        reservations:
          cpus: '0.3'
          memory: 512M

networks:
  pdp-network:
    name: pdp-network
    driver: bridge

volumes:
  postgres-init:
